namespace WinPods;

partial class Form1
{
    private System.ComponentModel.IContainer components = null;
    private TableLayoutPanel rootLayout;
    private Panel headerPanel;
    private Label titleLabel;
    private Label subtitleLabel;
    private Button refreshButton;
    private SplitContainer mainSplit;
    private Panel devicesPanel;
    private Label devicesTitleLabel;
    private Label deviceHintLabel;
    private ListView deviceListView;
    private ColumnHeader deviceNameColumn;
    private ColumnHeader deviceBatteryColumn;
    private ColumnHeader deviceSignalColumn;
    private ColumnHeader deviceSeenColumn;
    private ColumnHeader deviceAddressColumn;
    private Panel detailPanel;
    private Label modelLabel;
    private Label modelValueLabel;
    private TableLayoutPanel batteryGrid;
    private Panel leftBatteryPanel;
    private Panel rightBatteryPanel;
    private Panel caseBatteryPanel;
    private Label leftLabel;
    private Label leftBatteryLabel;
    private Label rightLabel;
    private Label rightBatteryLabel;
    private Label caseLabel;
    private Label caseBatteryLabel;
    private TableLayoutPanel metaGrid;
    private Label statusLabel;
    private Label statusValueLabel;
    private Label signalLabel;
    private Label signalValueLabel;
    private Label addressLabel;
    private Label addressValueLabel;
    private TextBox rawValueBox;
    private NotifyIcon notifyIcon;
    private ContextMenuStrip trayMenu;
    private ToolStripMenuItem openMenuItem;
    private ToolStripMenuItem refreshMenuItem;
    private ToolStripMenuItem exitMenuItem;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            scanner.Dispose();
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        rootLayout = new TableLayoutPanel();
        headerPanel = new Panel();
        titleLabel = new Label();
        subtitleLabel = new Label();
        refreshButton = new Button();
        mainSplit = new SplitContainer();
        devicesPanel = new Panel();
        devicesTitleLabel = new Label();
        deviceHintLabel = new Label();
        deviceListView = new ListView();
        deviceNameColumn = new ColumnHeader();
        deviceBatteryColumn = new ColumnHeader();
        deviceSignalColumn = new ColumnHeader();
        deviceSeenColumn = new ColumnHeader();
        deviceAddressColumn = new ColumnHeader();
        detailPanel = new Panel();
        modelLabel = new Label();
        modelValueLabel = new Label();
        batteryGrid = new TableLayoutPanel();
        leftBatteryPanel = new Panel();
        rightBatteryPanel = new Panel();
        caseBatteryPanel = new Panel();
        leftLabel = new Label();
        leftBatteryLabel = new Label();
        rightLabel = new Label();
        rightBatteryLabel = new Label();
        caseLabel = new Label();
        caseBatteryLabel = new Label();
        metaGrid = new TableLayoutPanel();
        statusLabel = new Label();
        statusValueLabel = new Label();
        signalLabel = new Label();
        signalValueLabel = new Label();
        addressLabel = new Label();
        addressValueLabel = new Label();
        rawValueBox = new TextBox();
        notifyIcon = new NotifyIcon(components);
        trayMenu = new ContextMenuStrip(components);
        openMenuItem = new ToolStripMenuItem();
        refreshMenuItem = new ToolStripMenuItem();
        exitMenuItem = new ToolStripMenuItem();
        rootLayout.SuspendLayout();
        headerPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)mainSplit).BeginInit();
        mainSplit.Panel1.SuspendLayout();
        mainSplit.Panel2.SuspendLayout();
        mainSplit.SuspendLayout();
        devicesPanel.SuspendLayout();
        detailPanel.SuspendLayout();
        batteryGrid.SuspendLayout();
        leftBatteryPanel.SuspendLayout();
        rightBatteryPanel.SuspendLayout();
        caseBatteryPanel.SuspendLayout();
        metaGrid.SuspendLayout();
        trayMenu.SuspendLayout();
        SuspendLayout();
        rootLayout.ColumnCount = 1;
        rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        rootLayout.Controls.Add(headerPanel, 0, 0);
        rootLayout.Controls.Add(mainSplit, 0, 1);
        rootLayout.Dock = DockStyle.Fill;
        rootLayout.Location = new Point(18, 18);
        rootLayout.Name = "rootLayout";
        rootLayout.RowCount = 2;
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 74F));
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        rootLayout.Size = new Size(884, 506);
        rootLayout.TabIndex = 0;
        headerPanel.Controls.Add(titleLabel);
        headerPanel.Controls.Add(subtitleLabel);
        headerPanel.Controls.Add(refreshButton);
        headerPanel.Dock = DockStyle.Fill;
        headerPanel.Location = new Point(0, 0);
        headerPanel.Margin = new Padding(0, 0, 0, 14);
        headerPanel.Name = "headerPanel";
        headerPanel.Size = new Size(884, 60);
        headerPanel.TabIndex = 0;
        titleLabel.AutoSize = true;
        titleLabel.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        titleLabel.Location = new Point(0, 0);
        titleLabel.Name = "titleLabel";
        titleLabel.Size = new Size(142, 41);
        titleLabel.TabIndex = 0;
        titleLabel.Text = "WinPods";
        subtitleLabel.AutoSize = true;
        subtitleLabel.ForeColor = Color.FromArgb(90, 98, 110);
        subtitleLabel.Location = new Point(3, 42);
        subtitleLabel.Name = "subtitleLabel";
        subtitleLabel.Size = new Size(243, 15);
        subtitleLabel.TabIndex = 1;
        subtitleLabel.Text = "Select your AirPods, then keep app in tray.";
        refreshButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        refreshButton.BackColor = Color.FromArgb(36, 120, 90);
        refreshButton.FlatAppearance.BorderSize = 0;
        refreshButton.FlatStyle = FlatStyle.Flat;
        refreshButton.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        refreshButton.ForeColor = Color.White;
        refreshButton.Location = new Point(754, 10);
        refreshButton.Name = "refreshButton";
        refreshButton.Size = new Size(128, 38);
        refreshButton.TabIndex = 2;
        refreshButton.Text = "Refresh";
        refreshButton.UseVisualStyleBackColor = false;
        refreshButton.Click += refreshButton_Click;
        mainSplit.Dock = DockStyle.Fill;
        mainSplit.FixedPanel = FixedPanel.Panel1;
        mainSplit.Location = new Point(0, 74);
        mainSplit.Margin = new Padding(0);
        mainSplit.Name = "mainSplit";
        mainSplit.Panel1.Controls.Add(devicesPanel);
        mainSplit.Panel1MinSize = 390;
        mainSplit.Panel2.Controls.Add(detailPanel);
        mainSplit.Panel2MinSize = 420;
        mainSplit.Size = new Size(884, 432);
        mainSplit.SplitterDistance = 410;
        mainSplit.SplitterWidth = 10;
        mainSplit.TabIndex = 1;
        devicesPanel.BackColor = Color.FromArgb(247, 248, 250);
        devicesPanel.Controls.Add(deviceListView);
        devicesPanel.Controls.Add(deviceHintLabel);
        devicesPanel.Controls.Add(devicesTitleLabel);
        devicesPanel.Dock = DockStyle.Fill;
        devicesPanel.Location = new Point(0, 0);
        devicesPanel.Name = "devicesPanel";
        devicesPanel.Padding = new Padding(14);
        devicesPanel.Size = new Size(410, 432);
        devicesPanel.TabIndex = 0;
        devicesTitleLabel.AutoSize = true;
        devicesTitleLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        devicesTitleLabel.Location = new Point(14, 14);
        devicesTitleLabel.Name = "devicesTitleLabel";
        devicesTitleLabel.Size = new Size(110, 21);
        devicesTitleLabel.TabIndex = 0;
        devicesTitleLabel.Text = "Found devices";
        deviceHintLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        deviceHintLabel.AutoEllipsis = true;
        deviceHintLabel.ForeColor = Color.FromArgb(90, 98, 110);
        deviceHintLabel.Location = new Point(17, 39);
        deviceHintLabel.Name = "deviceHintLabel";
        deviceHintLabel.Size = new Size(376, 22);
        deviceHintLabel.TabIndex = 1;
        deviceHintLabel.Text = "Open AirPods case near PC.";
        deviceListView.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        deviceListView.BorderStyle = BorderStyle.None;
        deviceListView.Columns.AddRange(new ColumnHeader[] { deviceNameColumn, deviceBatteryColumn, deviceSignalColumn, deviceSeenColumn, deviceAddressColumn });
        deviceListView.FullRowSelect = true;
        deviceListView.GridLines = true;
        deviceListView.HeaderStyle = ColumnHeaderStyle.Nonclickable;
        deviceListView.HideSelection = false;
        deviceListView.Location = new Point(14, 68);
        deviceListView.MultiSelect = false;
        deviceListView.Name = "deviceListView";
        deviceListView.Size = new Size(382, 350);
        deviceListView.TabIndex = 2;
        deviceListView.UseCompatibleStateImageBehavior = false;
        deviceListView.View = View.Details;
        deviceListView.SelectedIndexChanged += deviceListView_SelectedIndexChanged;
        deviceNameColumn.Text = "Name";
        deviceNameColumn.Width = 118;
        deviceBatteryColumn.Text = "Battery";
        deviceBatteryColumn.Width = 128;
        deviceSignalColumn.Text = "Signal";
        deviceSignalColumn.Width = 70;
        deviceSeenColumn.Text = "Seen";
        deviceSeenColumn.Width = 62;
        deviceAddressColumn.Text = "Address";
        deviceAddressColumn.Width = 128;
        detailPanel.BackColor = Color.White;
        detailPanel.Controls.Add(rawValueBox);
        detailPanel.Controls.Add(metaGrid);
        detailPanel.Controls.Add(batteryGrid);
        detailPanel.Controls.Add(modelValueLabel);
        detailPanel.Controls.Add(modelLabel);
        detailPanel.Dock = DockStyle.Fill;
        detailPanel.Location = new Point(0, 0);
        detailPanel.Name = "detailPanel";
        detailPanel.Padding = new Padding(20);
        detailPanel.Size = new Size(464, 432);
        detailPanel.TabIndex = 0;
        modelLabel.AutoSize = true;
        modelLabel.ForeColor = Color.FromArgb(90, 98, 110);
        modelLabel.Location = new Point(22, 18);
        modelLabel.Name = "modelLabel";
        modelLabel.Size = new Size(40, 15);
        modelLabel.TabIndex = 0;
        modelLabel.Text = "Model";
        modelValueLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        modelValueLabel.AutoEllipsis = true;
        modelValueLabel.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        modelValueLabel.Location = new Point(20, 36);
        modelValueLabel.Name = "modelValueLabel";
        modelValueLabel.Size = new Size(424, 38);
        modelValueLabel.TabIndex = 1;
        modelValueLabel.Text = "-";
        batteryGrid.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        batteryGrid.ColumnCount = 3;
        batteryGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.3333321F));
        batteryGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.3333321F));
        batteryGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.3333321F));
        batteryGrid.Controls.Add(leftBatteryPanel, 0, 0);
        batteryGrid.Controls.Add(rightBatteryPanel, 1, 0);
        batteryGrid.Controls.Add(caseBatteryPanel, 2, 0);
        batteryGrid.Location = new Point(20, 88);
        batteryGrid.Name = "batteryGrid";
        batteryGrid.RowCount = 1;
        batteryGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        batteryGrid.Size = new Size(424, 116);
        batteryGrid.TabIndex = 2;
        leftBatteryPanel.BackColor = Color.FromArgb(241, 250, 246);
        leftBatteryPanel.Controls.Add(leftBatteryLabel);
        leftBatteryPanel.Controls.Add(leftLabel);
        leftBatteryPanel.Dock = DockStyle.Fill;
        leftBatteryPanel.Margin = new Padding(0, 0, 8, 0);
        leftBatteryPanel.Padding = new Padding(12);
        leftBatteryPanel.TabIndex = 0;
        rightBatteryPanel.BackColor = Color.FromArgb(241, 247, 252);
        rightBatteryPanel.Controls.Add(rightBatteryLabel);
        rightBatteryPanel.Controls.Add(rightLabel);
        rightBatteryPanel.Dock = DockStyle.Fill;
        rightBatteryPanel.Margin = new Padding(4, 0, 4, 0);
        rightBatteryPanel.Padding = new Padding(12);
        rightBatteryPanel.TabIndex = 1;
        caseBatteryPanel.BackColor = Color.FromArgb(252, 248, 240);
        caseBatteryPanel.Controls.Add(caseBatteryLabel);
        caseBatteryPanel.Controls.Add(caseLabel);
        caseBatteryPanel.Dock = DockStyle.Fill;
        caseBatteryPanel.Margin = new Padding(8, 0, 0, 0);
        caseBatteryPanel.Padding = new Padding(12);
        caseBatteryPanel.TabIndex = 2;
        leftLabel.AutoSize = true;
        leftLabel.ForeColor = Color.FromArgb(80, 88, 98);
        leftLabel.Location = new Point(12, 12);
        leftLabel.Text = "Left";
        leftBatteryLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        leftBatteryLabel.Font = new Font("Segoe UI", 17F, FontStyle.Bold);
        leftBatteryLabel.Location = new Point(12, 42);
        leftBatteryLabel.Size = new Size(112, 54);
        leftBatteryLabel.Text = "-";
        leftBatteryLabel.TextAlign = ContentAlignment.MiddleLeft;
        rightLabel.AutoSize = true;
        rightLabel.ForeColor = Color.FromArgb(80, 88, 98);
        rightLabel.Location = new Point(12, 12);
        rightLabel.Text = "Right";
        rightBatteryLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        rightBatteryLabel.Font = new Font("Segoe UI", 17F, FontStyle.Bold);
        rightBatteryLabel.Location = new Point(12, 42);
        rightBatteryLabel.Size = new Size(112, 54);
        rightBatteryLabel.Text = "-";
        rightBatteryLabel.TextAlign = ContentAlignment.MiddleLeft;
        caseLabel.AutoSize = true;
        caseLabel.ForeColor = Color.FromArgb(80, 88, 98);
        caseLabel.Location = new Point(12, 12);
        caseLabel.Text = "Case";
        caseBatteryLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        caseBatteryLabel.Font = new Font("Segoe UI", 17F, FontStyle.Bold);
        caseBatteryLabel.Location = new Point(12, 42);
        caseBatteryLabel.Size = new Size(112, 54);
        caseBatteryLabel.Text = "-";
        caseBatteryLabel.TextAlign = ContentAlignment.MiddleLeft;
        metaGrid.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        metaGrid.ColumnCount = 2;
        metaGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 78F));
        metaGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        metaGrid.Controls.Add(statusLabel, 0, 0);
        metaGrid.Controls.Add(statusValueLabel, 1, 0);
        metaGrid.Controls.Add(signalLabel, 0, 1);
        metaGrid.Controls.Add(signalValueLabel, 1, 1);
        metaGrid.Controls.Add(addressLabel, 0, 2);
        metaGrid.Controls.Add(addressValueLabel, 1, 2);
        metaGrid.Location = new Point(20, 224);
        metaGrid.Name = "metaGrid";
        metaGrid.RowCount = 3;
        metaGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        metaGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        metaGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        metaGrid.Size = new Size(424, 90);
        metaGrid.TabIndex = 3;
        foreach (var label in new[] { statusLabel, signalLabel, addressLabel })
        {
            label.Dock = DockStyle.Fill;
            label.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            label.ForeColor = Color.FromArgb(80, 88, 98);
            label.TextAlign = ContentAlignment.MiddleLeft;
        }
        statusLabel.Text = "Status";
        signalLabel.Text = "Signal";
        addressLabel.Text = "Address";
        foreach (var label in new[] { statusValueLabel, signalValueLabel, addressValueLabel })
        {
            label.AutoEllipsis = true;
            label.Dock = DockStyle.Fill;
            label.TextAlign = ContentAlignment.MiddleLeft;
        }
        rawValueBox.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        rawValueBox.BackColor = Color.FromArgb(250, 251, 252);
        rawValueBox.BorderStyle = BorderStyle.FixedSingle;
        rawValueBox.Location = new Point(20, 332);
        rawValueBox.Multiline = true;
        rawValueBox.Name = "rawValueBox";
        rawValueBox.ReadOnly = true;
        rawValueBox.ScrollBars = ScrollBars.Vertical;
        rawValueBox.Size = new Size(424, 80);
        rawValueBox.TabIndex = 4;
        trayMenu.Items.AddRange(new ToolStripItem[] { openMenuItem, refreshMenuItem, exitMenuItem });
        openMenuItem.Text = "Open";
        openMenuItem.Click += openMenuItem_Click;
        refreshMenuItem.Text = "Refresh";
        refreshMenuItem.Click += refreshMenuItem_Click;
        exitMenuItem.Text = "Exit";
        exitMenuItem.Click += exitMenuItem_Click;
        notifyIcon.ContextMenuStrip = trayMenu;
        notifyIcon.Text = "WinPods";
        notifyIcon.Visible = true;
        notifyIcon.DoubleClick += notifyIcon_DoubleClick;
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.White;
        ClientSize = new Size(920, 542);
        Controls.Add(rootLayout);
        Font = new Font("Segoe UI", 9F);
        MinimumSize = new Size(860, 520);
        Name = "Form1";
        Padding = new Padding(18);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "WinPods";
        rootLayout.ResumeLayout(false);
        headerPanel.ResumeLayout(false);
        headerPanel.PerformLayout();
        mainSplit.Panel1.ResumeLayout(false);
        mainSplit.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)mainSplit).EndInit();
        mainSplit.ResumeLayout(false);
        devicesPanel.ResumeLayout(false);
        devicesPanel.PerformLayout();
        detailPanel.ResumeLayout(false);
        detailPanel.PerformLayout();
        batteryGrid.ResumeLayout(false);
        leftBatteryPanel.ResumeLayout(false);
        leftBatteryPanel.PerformLayout();
        rightBatteryPanel.ResumeLayout(false);
        rightBatteryPanel.PerformLayout();
        caseBatteryPanel.ResumeLayout(false);
        caseBatteryPanel.PerformLayout();
        metaGrid.ResumeLayout(false);
        trayMenu.ResumeLayout(false);
        ResumeLayout(false);
    }
}
