namespace WinPods;

partial class Form1
{
    private System.ComponentModel.IContainer components = null;
    private TableLayoutPanel rootLayout;
    private Panel headerPanel;
    private Label titleLabel;
    private Label subtitleLabel;
    private Label themeLabel;
    private ThemeToggleSwitch themeToggleSwitch;
    private Button refreshButton;
    private SplitContainer mainSplit;
    private Panel devicesPanel;
    private Label devicesTitleLabel;
    private Label deviceHintLabel;
    private Button sortButton;
    private CheckBox pinnedOnlyCheckBox;
    private ContextMenuStrip sortMenu;
    private ToolStripMenuItem sortSignalStrongItem;
    private ToolStripMenuItem sortSignalWeakItem;
    private ToolStripMenuItem sortBatteryItem;
    private ToolStripMenuItem sortConnectedItem;
    private ToolStripMenuItem sortSeenItem;
    private ToolStripMenuItem sortNameItem;
    private BufferedFlowLayoutPanel deviceCardsPanel;
    private ListView deviceListView;
    private ColumnHeader deviceNameColumn;
    private ColumnHeader deviceConnectedColumn;
    private ColumnHeader deviceBatteryColumn;
    private ColumnHeader deviceSignalColumn;
    private ColumnHeader deviceSeenColumn;
    private ColumnHeader deviceAddressColumn;
    private Panel detailPanel;
    private Panel detailContentPanel;
    private Label modelLabel;
    private Label modelValueLabel;
    private TableLayoutPanel batteryGrid;
    private ModernPanel leftBatteryPanel;
    private ModernPanel rightBatteryPanel;
    private ModernPanel caseBatteryPanel;
    private Label leftLabel;
    private Label leftBatteryLabel;
    private Label rightLabel;
    private Label rightBatteryLabel;
    private Label caseLabel;
    private Label caseBatteryLabel;
    private Label listeningModeLabel;
    private Button pinDeviceButton;
    private TableLayoutPanel listeningModePanel;
    private Button transparencyButton;
    private Button adaptiveButton;
    private Button noiseCancelButton;
    private Label listeningModeStatusLabel;
    private ModernPanel callQualityPanel;
    private Label callQualityTitleLabel;
    private CheckBox callQualityGuardCheckBox;
    private Label callQualityStatusLabel;
    private Label callQualityDetailLabel;
    private Button callQualityFixButton;
    private Button callQualitySettingsButton;
    private TableLayoutPanel metaGrid;
    private Label statusLabel;
    private Label statusValueLabel;
    private Label connectedLabel;
    private Label connectedValueLabel;
    private Label signalLabel;
    private Label signalValueLabel;
    private Label addressLabel;
    private Label addressValueLabel;
    private TextBox rawValueBox;
    private NotifyIcon notifyIcon;
    private ContextMenuStrip trayMenu;
    private ToolStripMenuItem openMenuItem;
    private ToolStripMenuItem refreshMenuItem;
    private ToolStripMenuItem trayListeningModeMenuItem;
    private ToolStripMenuItem trayTransparencyMenuItem;
    private ToolStripMenuItem trayAdaptiveMenuItem;
    private ToolStripMenuItem trayNoiseCancelMenuItem;
    private ToolStripSeparator trayCallQualitySeparator;
    private ToolStripMenuItem trayCallQualityGuardMenuItem;
    private ToolStripMenuItem trayCallQualityEnabledMenuItem;
    private ToolStripMenuItem trayApplyCallQualityFixMenuItem;
    private ToolStripMenuItem trayOpenSoundSettingsMenuItem;
    private ToolStripMenuItem exitMenuItem;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            connectedRefreshTimer.Dispose();
            callQualityGuardTimer.Dispose();
            autoScanPauseTimer.Dispose();
            scanner.Dispose();
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        rootLayout = new TableLayoutPanel();
        headerPanel = new Panel();
        titleLabel = new Label();
        subtitleLabel = new Label();
        themeLabel = new Label();
        themeToggleSwitch = new ThemeToggleSwitch();
        refreshButton = new Button();
        mainSplit = new SplitContainer();
        devicesPanel = new Panel();
        devicesTitleLabel = new Label();
        deviceHintLabel = new Label();
        sortButton = new Button();
        pinnedOnlyCheckBox = new CheckBox();
        sortMenu = new ContextMenuStrip(components);
        sortSignalStrongItem = new ToolStripMenuItem();
        sortSignalWeakItem = new ToolStripMenuItem();
        sortBatteryItem = new ToolStripMenuItem();
        sortConnectedItem = new ToolStripMenuItem();
        sortSeenItem = new ToolStripMenuItem();
        sortNameItem = new ToolStripMenuItem();
        deviceCardsPanel = new BufferedFlowLayoutPanel();
        deviceListView = new ListView();
        deviceNameColumn = new ColumnHeader();
        deviceConnectedColumn = new ColumnHeader();
        deviceBatteryColumn = new ColumnHeader();
        deviceSignalColumn = new ColumnHeader();
        deviceSeenColumn = new ColumnHeader();
        deviceAddressColumn = new ColumnHeader();
        detailPanel = new Panel();
        detailContentPanel = new Panel();
        modelLabel = new Label();
        modelValueLabel = new Label();
        batteryGrid = new TableLayoutPanel();
        leftBatteryPanel = new ModernPanel();
        rightBatteryPanel = new ModernPanel();
        caseBatteryPanel = new ModernPanel();
        leftLabel = new Label();
        leftBatteryLabel = new Label();
        rightLabel = new Label();
        rightBatteryLabel = new Label();
        caseLabel = new Label();
        caseBatteryLabel = new Label();
        listeningModeLabel = new Label();
        pinDeviceButton = new Button();
        listeningModePanel = new TableLayoutPanel();
        transparencyButton = new Button();
        adaptiveButton = new Button();
        noiseCancelButton = new Button();
        listeningModeStatusLabel = new Label();
        callQualityPanel = new ModernPanel();
        callQualityTitleLabel = new Label();
        callQualityGuardCheckBox = new CheckBox();
        callQualityStatusLabel = new Label();
        callQualityDetailLabel = new Label();
        callQualityFixButton = new Button();
        callQualitySettingsButton = new Button();
        metaGrid = new TableLayoutPanel();
        statusLabel = new Label();
        statusValueLabel = new Label();
        connectedLabel = new Label();
        connectedValueLabel = new Label();
        signalLabel = new Label();
        signalValueLabel = new Label();
        addressLabel = new Label();
        addressValueLabel = new Label();
        rawValueBox = new TextBox();
        notifyIcon = new NotifyIcon(components);
        trayMenu = new ContextMenuStrip(components);
        openMenuItem = new ToolStripMenuItem();
        refreshMenuItem = new ToolStripMenuItem();
        trayListeningModeMenuItem = new ToolStripMenuItem();
        trayTransparencyMenuItem = new ToolStripMenuItem();
        trayAdaptiveMenuItem = new ToolStripMenuItem();
        trayNoiseCancelMenuItem = new ToolStripMenuItem();
        trayCallQualitySeparator = new ToolStripSeparator();
        trayCallQualityGuardMenuItem = new ToolStripMenuItem();
        trayCallQualityEnabledMenuItem = new ToolStripMenuItem();
        trayApplyCallQualityFixMenuItem = new ToolStripMenuItem();
        trayOpenSoundSettingsMenuItem = new ToolStripMenuItem();
        exitMenuItem = new ToolStripMenuItem();
        rootLayout.SuspendLayout();
        headerPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)mainSplit).BeginInit();
        mainSplit.Panel1.SuspendLayout();
        mainSplit.Panel2.SuspendLayout();
        mainSplit.SuspendLayout();
        devicesPanel.SuspendLayout();
        sortMenu.SuspendLayout();
        detailPanel.SuspendLayout();
        batteryGrid.SuspendLayout();
        leftBatteryPanel.SuspendLayout();
        rightBatteryPanel.SuspendLayout();
        caseBatteryPanel.SuspendLayout();
        listeningModePanel.SuspendLayout();
        callQualityPanel.SuspendLayout();
        metaGrid.SuspendLayout();
        trayMenu.SuspendLayout();
        SuspendLayout();
        rootLayout.ColumnCount = 1;
        rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        rootLayout.Controls.Add(headerPanel, 0, 0);
        rootLayout.Controls.Add(mainSplit, 0, 1);
        rootLayout.Dock = DockStyle.Fill;
        rootLayout.Location = new Point(18, 18);
        rootLayout.Name = "rootLayout";
        rootLayout.RowCount = 2;
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 74F));
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        rootLayout.Size = new Size(1064, 526);
        rootLayout.TabIndex = 0;
        headerPanel.Controls.Add(titleLabel);
        headerPanel.Controls.Add(subtitleLabel);
        headerPanel.Controls.Add(themeToggleSwitch);
        headerPanel.Controls.Add(themeLabel);
        headerPanel.Controls.Add(refreshButton);
        headerPanel.Dock = DockStyle.Fill;
        headerPanel.Location = new Point(0, 0);
        headerPanel.Margin = new Padding(0, 0, 0, 14);
        headerPanel.Name = "headerPanel";
        headerPanel.Size = new Size(1064, 60);
        headerPanel.TabIndex = 0;
        titleLabel.AutoSize = true;
        titleLabel.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        titleLabel.Location = new Point(0, 0);
        titleLabel.Name = "titleLabel";
        titleLabel.Size = new Size(142, 41);
        titleLabel.TabIndex = 0;
        titleLabel.Text = "WinPods";
        subtitleLabel.AutoSize = true;
        subtitleLabel.ForeColor = Color.FromArgb(90, 98, 110);
        subtitleLabel.Location = new Point(3, 42);
        subtitleLabel.Name = "subtitleLabel";
        subtitleLabel.Size = new Size(243, 15);
        subtitleLabel.TabIndex = 1;
        subtitleLabel.Text = "Select your AirPods, then keep app in tray.";
        themeLabel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        themeLabel.AutoEllipsis = false;
        themeLabel.AutoSize = false;
        themeLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        themeLabel.ForeColor = Color.FromArgb(80, 88, 98);
        themeLabel.Location = new Point(750, 18);
        themeLabel.Name = "themeLabel";
        themeLabel.Size = new Size(96, 19);
        themeLabel.TabIndex = 2;
        themeLabel.Text = "Black theme";
        themeLabel.TextAlign = ContentAlignment.MiddleRight;
        themeToggleSwitch.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        themeToggleSwitch.BorderColor = Color.FromArgb(80, 88, 98);
        themeToggleSwitch.Location = new Point(858, 14);
        themeToggleSwitch.Name = "themeToggleSwitch";
        themeToggleSwitch.Size = new Size(54, 28);
        themeToggleSwitch.TabIndex = 3;
        themeToggleSwitch.CheckedChanged += themeToggleSwitch_CheckedChanged;
        refreshButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        refreshButton.BackColor = Color.FromArgb(36, 120, 90);
        refreshButton.FlatAppearance.BorderSize = 0;
        refreshButton.FlatStyle = FlatStyle.Flat;
        refreshButton.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        refreshButton.ForeColor = Color.White;
        refreshButton.Location = new Point(934, 10);
        refreshButton.Name = "refreshButton";
        refreshButton.Size = new Size(128, 38);
        refreshButton.TabIndex = 4;
        refreshButton.Text = "Stop scan";
        refreshButton.UseVisualStyleBackColor = false;
        refreshButton.Click += refreshButton_Click;
        mainSplit.Dock = DockStyle.Fill;
        mainSplit.FixedPanel = FixedPanel.Panel1;
        mainSplit.Location = new Point(0, 74);
        mainSplit.Margin = new Padding(0);
        mainSplit.Name = "mainSplit";
        mainSplit.Panel1.Controls.Add(devicesPanel);
        mainSplit.Panel1MinSize = 560;
        mainSplit.Panel2.Controls.Add(detailPanel);
        mainSplit.Panel2MinSize = 260;
        mainSplit.Size = new Size(1064, 452);
        mainSplit.SplitterDistance = 580;
        mainSplit.SplitterWidth = 10;
        mainSplit.TabIndex = 1;
        mainSplit.SplitterMoved += mainSplit_SplitterMoved;
        devicesPanel.BackColor = Color.FromArgb(247, 248, 250);
        devicesPanel.Controls.Add(deviceCardsPanel);
        devicesPanel.Controls.Add(sortButton);
        devicesPanel.Controls.Add(pinnedOnlyCheckBox);
        devicesPanel.Controls.Add(deviceHintLabel);
        devicesPanel.Controls.Add(devicesTitleLabel);
        devicesPanel.Dock = DockStyle.Fill;
        devicesPanel.Location = new Point(0, 0);
        devicesPanel.Name = "devicesPanel";
        devicesPanel.Padding = new Padding(14);
        devicesPanel.Size = new Size(580, 452);
        devicesPanel.TabIndex = 0;
        devicesTitleLabel.AutoSize = true;
        devicesTitleLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        devicesTitleLabel.Location = new Point(14, 14);
        devicesTitleLabel.Name = "devicesTitleLabel";
        devicesTitleLabel.Size = new Size(110, 21);
        devicesTitleLabel.TabIndex = 0;
        devicesTitleLabel.Text = "Found devices";
        deviceHintLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        deviceHintLabel.AutoEllipsis = true;
        deviceHintLabel.ForeColor = Color.FromArgb(90, 98, 110);
        deviceHintLabel.Location = new Point(17, 39);
        deviceHintLabel.Name = "deviceHintLabel";
        deviceHintLabel.Size = new Size(402, 22);
        deviceHintLabel.TabIndex = 1;
        deviceHintLabel.Text = "Open AirPods case near PC.";
        sortButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        sortButton.BackColor = Color.White;
        sortButton.ContextMenuStrip = sortMenu;
        sortButton.FlatAppearance.BorderColor = Color.FromArgb(205, 213, 224);
        sortButton.FlatStyle = FlatStyle.Flat;
        sortButton.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        sortButton.ForeColor = Color.FromArgb(28, 34, 42);
        sortButton.Location = new Point(422, 31);
        sortButton.Name = "sortButton";
        sortButton.Size = new Size(140, 30);
        sortButton.TabIndex = 2;
        sortButton.Text = "Sort: Signal down";
        sortButton.UseVisualStyleBackColor = false;
        sortButton.Click += sortButton_Click;
        sortMenu.Items.AddRange(new ToolStripItem[] { sortSignalStrongItem, sortSignalWeakItem, sortBatteryItem, sortConnectedItem, sortSeenItem, sortNameItem });
        sortSignalStrongItem.Text = "Signal: strongest first";
        sortSignalStrongItem.Click += sortSignalStrongItem_Click;
        sortSignalWeakItem.Text = "Signal: weakest first";
        sortSignalWeakItem.Click += sortSignalWeakItem_Click;
        sortBatteryItem.Text = "Battery: highest first";
        sortBatteryItem.Click += sortBatteryItem_Click;
        sortConnectedItem.Text = "Bluetooth: connected first";
        sortConnectedItem.Click += sortConnectedItem_Click;
        sortSeenItem.Text = "Last seen: newest first";
        sortSeenItem.Click += sortSeenItem_Click;
        sortNameItem.Text = "Name: A to Z";
        sortNameItem.Click += sortNameItem_Click;
        pinnedOnlyCheckBox.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        pinnedOnlyCheckBox.AutoSize = true;
        pinnedOnlyCheckBox.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
        pinnedOnlyCheckBox.ForeColor = Color.FromArgb(80, 88, 98);
        pinnedOnlyCheckBox.Location = new Point(422, 10);
        pinnedOnlyCheckBox.Name = "pinnedOnlyCheckBox";
        pinnedOnlyCheckBox.Size = new Size(121, 19);
        pinnedOnlyCheckBox.TabIndex = 3;
        pinnedOnlyCheckBox.Text = "Only my AirPods";
        pinnedOnlyCheckBox.UseVisualStyleBackColor = true;
        pinnedOnlyCheckBox.CheckedChanged += pinnedOnlyCheckBox_CheckedChanged;
        deviceCardsPanel.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        deviceCardsPanel.AutoScroll = true;
        deviceCardsPanel.BackColor = Color.FromArgb(247, 248, 250);
        deviceCardsPanel.FlowDirection = FlowDirection.LeftToRight;
        deviceCardsPanel.Location = new Point(14, 68);
        deviceCardsPanel.Name = "deviceCardsPanel";
        deviceCardsPanel.Size = new Size(552, 370);
        deviceCardsPanel.TabIndex = 3;
        deviceCardsPanel.WrapContents = true;
        deviceListView.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        deviceListView.BorderStyle = BorderStyle.None;
        deviceListView.Columns.AddRange(new ColumnHeader[] { deviceNameColumn, deviceConnectedColumn, deviceBatteryColumn, deviceSignalColumn, deviceSeenColumn, deviceAddressColumn });
        deviceListView.FullRowSelect = true;
        deviceListView.GridLines = true;
        deviceListView.HeaderStyle = ColumnHeaderStyle.Clickable;
        deviceListView.HideSelection = false;
        deviceListView.Location = new Point(14, 68);
        deviceListView.MultiSelect = false;
        deviceListView.Name = "deviceListView";
        deviceListView.Size = new Size(552, 370);
        deviceListView.TabIndex = 2;
        deviceListView.UseCompatibleStateImageBehavior = false;
        deviceListView.View = View.Details;
        deviceListView.ColumnClick += deviceListView_ColumnClick;
        deviceListView.SelectedIndexChanged += deviceListView_SelectedIndexChanged;
        deviceNameColumn.Text = "Name";
        deviceNameColumn.Width = 112;
        deviceConnectedColumn.Text = "Windows";
        deviceConnectedColumn.Width = 92;
        deviceBatteryColumn.Text = "Battery";
        deviceBatteryColumn.Width = 128;
        deviceSignalColumn.Text = "Signal";
        deviceSignalColumn.Width = 70;
        deviceSeenColumn.Text = "Seen";
        deviceSeenColumn.Width = 62;
        deviceAddressColumn.Text = "Address";
        deviceAddressColumn.Width = 128;
        detailPanel.BackColor = Color.White;
        detailPanel.AutoScroll = true;
        detailPanel.Dock = DockStyle.Fill;
        detailPanel.Controls.Add(detailContentPanel);
        detailPanel.Location = new Point(0, 0);
        detailPanel.Name = "detailPanel";
        detailPanel.Size = new Size(474, 452);
        detailPanel.TabIndex = 0;
        detailContentPanel.Controls.Add(rawValueBox);
        detailContentPanel.Controls.Add(metaGrid);
        detailContentPanel.Controls.Add(callQualityPanel);
        detailContentPanel.Controls.Add(listeningModeStatusLabel);
        detailContentPanel.Controls.Add(listeningModePanel);
        detailContentPanel.Controls.Add(pinDeviceButton);
        detailContentPanel.Controls.Add(listeningModeLabel);
        detailContentPanel.Controls.Add(batteryGrid);
        detailContentPanel.Controls.Add(modelValueLabel);
        detailContentPanel.Controls.Add(modelLabel);
        detailContentPanel.Location = new Point(0, 0);
        detailContentPanel.MinimumSize = new Size(460, 760);
        detailContentPanel.Name = "detailContentPanel";
        detailContentPanel.Padding = new Padding(20);
        detailContentPanel.Size = new Size(474, 760);
        detailContentPanel.TabIndex = 0;
        modelLabel.AutoSize = true;
        modelLabel.ForeColor = Color.FromArgb(90, 98, 110);
        modelLabel.Location = new Point(22, 18);
        modelLabel.Name = "modelLabel";
        modelLabel.Size = new Size(40, 15);
        modelLabel.TabIndex = 0;
        modelLabel.Text = "Model";
        modelValueLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        modelValueLabel.AutoEllipsis = true;
        modelValueLabel.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        modelValueLabel.Location = new Point(20, 36);
        modelValueLabel.Name = "modelValueLabel";
        modelValueLabel.Size = new Size(424, 38);
        modelValueLabel.TabIndex = 1;
        modelValueLabel.Text = "-";
        batteryGrid.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        batteryGrid.ColumnCount = 3;
        batteryGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.3333321F));
        batteryGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.3333321F));
        batteryGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.3333321F));
        batteryGrid.Controls.Add(leftBatteryPanel, 0, 0);
        batteryGrid.Controls.Add(rightBatteryPanel, 1, 0);
        batteryGrid.Controls.Add(caseBatteryPanel, 2, 0);
        batteryGrid.Location = new Point(20, 88);
        batteryGrid.Name = "batteryGrid";
        batteryGrid.RowCount = 1;
        batteryGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        batteryGrid.Size = new Size(424, 116);
        batteryGrid.TabIndex = 2;
        leftBatteryPanel.BackColor = Color.FromArgb(241, 250, 246);
        leftBatteryPanel.BorderColor = Color.FromArgb(219, 229, 224);
        leftBatteryPanel.Controls.Add(leftLabel);
        leftBatteryPanel.Controls.Add(leftBatteryLabel);
        leftBatteryPanel.Dock = DockStyle.Fill;
        leftBatteryPanel.FillColor = Color.FromArgb(245, 252, 249);
        leftBatteryPanel.FillColor2 = Color.FromArgb(235, 247, 241);
        leftBatteryPanel.Margin = new Padding(0, 0, 8, 0);
        leftBatteryPanel.Padding = new Padding(12);
        leftBatteryPanel.Radius = 18;
        leftBatteryPanel.TabIndex = 0;
        rightBatteryPanel.BackColor = Color.FromArgb(241, 247, 252);
        rightBatteryPanel.BorderColor = Color.FromArgb(217, 226, 235);
        rightBatteryPanel.Controls.Add(rightLabel);
        rightBatteryPanel.Controls.Add(rightBatteryLabel);
        rightBatteryPanel.Dock = DockStyle.Fill;
        rightBatteryPanel.FillColor = Color.FromArgb(246, 250, 253);
        rightBatteryPanel.FillColor2 = Color.FromArgb(235, 244, 251);
        rightBatteryPanel.Margin = new Padding(4, 0, 4, 0);
        rightBatteryPanel.Padding = new Padding(12);
        rightBatteryPanel.Radius = 18;
        rightBatteryPanel.TabIndex = 1;
        caseBatteryPanel.BackColor = Color.FromArgb(252, 248, 240);
        caseBatteryPanel.BorderColor = Color.FromArgb(234, 225, 208);
        caseBatteryPanel.Controls.Add(caseLabel);
        caseBatteryPanel.Controls.Add(caseBatteryLabel);
        caseBatteryPanel.Dock = DockStyle.Fill;
        caseBatteryPanel.FillColor = Color.FromArgb(253, 250, 245);
        caseBatteryPanel.FillColor2 = Color.FromArgb(249, 242, 229);
        caseBatteryPanel.Margin = new Padding(8, 0, 0, 0);
        caseBatteryPanel.Padding = new Padding(12);
        caseBatteryPanel.Radius = 18;
        caseBatteryPanel.TabIndex = 2;
        leftLabel.AutoSize = true;
        leftLabel.Dock = DockStyle.Top;
        leftLabel.ForeColor = Color.FromArgb(80, 88, 98);
        leftLabel.Location = new Point(12, 12);
        leftLabel.Padding = new Padding(0, 0, 0, 8);
        leftLabel.Size = new Size(117, 27);
        leftLabel.Text = "Left";
        leftBatteryLabel.AutoEllipsis = false;
        leftBatteryLabel.Dock = DockStyle.Fill;
        leftBatteryLabel.Font = new Font("Segoe UI", 17F, FontStyle.Bold);
        leftBatteryLabel.Location = new Point(12, 27);
        leftBatteryLabel.Margin = new Padding(0);
        leftBatteryLabel.Size = new Size(117, 77);
        leftBatteryLabel.Text = "-";
        leftBatteryLabel.TextAlign = ContentAlignment.MiddleLeft;
        rightLabel.AutoSize = true;
        rightLabel.Dock = DockStyle.Top;
        rightLabel.ForeColor = Color.FromArgb(80, 88, 98);
        rightLabel.Location = new Point(12, 12);
        rightLabel.Padding = new Padding(0, 0, 0, 8);
        rightLabel.Size = new Size(117, 27);
        rightLabel.Text = "Right";
        rightBatteryLabel.AutoEllipsis = false;
        rightBatteryLabel.Dock = DockStyle.Fill;
        rightBatteryLabel.Font = new Font("Segoe UI", 17F, FontStyle.Bold);
        rightBatteryLabel.Location = new Point(12, 27);
        rightBatteryLabel.Margin = new Padding(0);
        rightBatteryLabel.Size = new Size(117, 77);
        rightBatteryLabel.Text = "-";
        rightBatteryLabel.TextAlign = ContentAlignment.MiddleLeft;
        caseLabel.AutoSize = true;
        caseLabel.Dock = DockStyle.Top;
        caseLabel.ForeColor = Color.FromArgb(80, 88, 98);
        caseLabel.Location = new Point(12, 12);
        caseLabel.Padding = new Padding(0, 0, 0, 8);
        caseLabel.Size = new Size(117, 27);
        caseLabel.Text = "Case";
        caseBatteryLabel.AutoEllipsis = false;
        caseBatteryLabel.Dock = DockStyle.Fill;
        caseBatteryLabel.Font = new Font("Segoe UI", 17F, FontStyle.Bold);
        caseBatteryLabel.Location = new Point(12, 27);
        caseBatteryLabel.Margin = new Padding(0);
        caseBatteryLabel.Size = new Size(117, 77);
        caseBatteryLabel.Text = "-";
        caseBatteryLabel.TextAlign = ContentAlignment.MiddleLeft;
        listeningModeLabel.AutoSize = true;
        listeningModeLabel.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        listeningModeLabel.ForeColor = Color.FromArgb(80, 88, 98);
        listeningModeLabel.Location = new Point(20, 222);
        listeningModeLabel.Name = "listeningModeLabel";
        listeningModeLabel.Size = new Size(102, 19);
        listeningModeLabel.TabIndex = 3;
        listeningModeLabel.Text = "Listening mode";
        pinDeviceButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        pinDeviceButton.BackColor = Color.White;
        pinDeviceButton.FlatAppearance.BorderColor = Color.FromArgb(205, 213, 224);
        pinDeviceButton.FlatStyle = FlatStyle.Flat;
        pinDeviceButton.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
        pinDeviceButton.ForeColor = Color.FromArgb(28, 34, 42);
        pinDeviceButton.Location = new Point(314, 216);
        pinDeviceButton.Name = "pinDeviceButton";
        pinDeviceButton.Size = new Size(130, 28);
        pinDeviceButton.TabIndex = 4;
        pinDeviceButton.Text = "Pin as mine";
        pinDeviceButton.UseVisualStyleBackColor = false;
        pinDeviceButton.Click += pinDeviceButton_Click;
        listeningModePanel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        listeningModePanel.ColumnCount = 3;
        listeningModePanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.3333321F));
        listeningModePanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.3333321F));
        listeningModePanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.3333321F));
        listeningModePanel.Controls.Add(transparencyButton, 0, 0);
        listeningModePanel.Controls.Add(adaptiveButton, 1, 0);
        listeningModePanel.Controls.Add(noiseCancelButton, 2, 0);
        listeningModePanel.Location = new Point(20, 248);
        listeningModePanel.Name = "listeningModePanel";
        listeningModePanel.RowCount = 1;
        listeningModePanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        listeningModePanel.Size = new Size(424, 48);
        listeningModePanel.TabIndex = 5;
        foreach (var button in new[] { transparencyButton, adaptiveButton, noiseCancelButton })
        {
            button.Dock = DockStyle.Fill;
            button.FlatAppearance.BorderColor = Color.FromArgb(205, 213, 224);
            button.FlatStyle = FlatStyle.Flat;
            button.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            button.Margin = new Padding(0, 0, 8, 0);
            button.UseVisualStyleBackColor = false;
        }
        transparencyButton.BackColor = Color.FromArgb(241, 250, 246);
        transparencyButton.Name = "transparencyButton";
        transparencyButton.TabIndex = 0;
        transparencyButton.Text = "Transparency";
        transparencyButton.Click += transparencyButton_Click;
        adaptiveButton.BackColor = Color.FromArgb(241, 247, 252);
        adaptiveButton.Name = "adaptiveButton";
        adaptiveButton.TabIndex = 1;
        adaptiveButton.Text = "Adaptive";
        adaptiveButton.Click += adaptiveButton_Click;
        noiseCancelButton.BackColor = Color.FromArgb(248, 245, 255);
        noiseCancelButton.Margin = new Padding(0);
        noiseCancelButton.Name = "noiseCancelButton";
        noiseCancelButton.TabIndex = 2;
        noiseCancelButton.Text = "Noise Cancel";
        noiseCancelButton.Click += noiseCancelButton_Click;
        listeningModeStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        listeningModeStatusLabel.AutoEllipsis = false;
        listeningModeStatusLabel.ForeColor = Color.FromArgb(90, 98, 110);
        listeningModeStatusLabel.Location = new Point(20, 304);
        listeningModeStatusLabel.Name = "listeningModeStatusLabel";
        listeningModeStatusLabel.Size = new Size(424, 42);
        listeningModeStatusLabel.TabIndex = 5;
        listeningModeStatusLabel.Text = "Connect AirPods in Windows Bluetooth to control mode.";
        callQualityPanel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        callQualityPanel.BackColor = Color.FromArgb(245, 249, 246);
        callQualityPanel.BorderColor = Color.FromArgb(218, 228, 222);
        callQualityPanel.BorderStyle = BorderStyle.None;
        callQualityPanel.Controls.Add(callQualitySettingsButton);
        callQualityPanel.Controls.Add(callQualityFixButton);
        callQualityPanel.Controls.Add(callQualityDetailLabel);
        callQualityPanel.Controls.Add(callQualityStatusLabel);
        callQualityPanel.Controls.Add(callQualityGuardCheckBox);
        callQualityPanel.Controls.Add(callQualityTitleLabel);
        callQualityPanel.FillColor = Color.FromArgb(248, 252, 250);
        callQualityPanel.FillColor2 = Color.FromArgb(238, 248, 242);
        callQualityPanel.Location = new Point(20, 356);
        callQualityPanel.Name = "callQualityPanel";
        callQualityPanel.Radius = 20;
        callQualityPanel.Size = new Size(424, 128);
        callQualityPanel.TabIndex = 6;
        callQualityTitleLabel.AutoSize = true;
        callQualityTitleLabel.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        callQualityTitleLabel.ForeColor = Color.FromArgb(28, 34, 42);
        callQualityTitleLabel.Location = new Point(12, 9);
        callQualityTitleLabel.Name = "callQualityTitleLabel";
        callQualityTitleLabel.Size = new Size(121, 19);
        callQualityTitleLabel.TabIndex = 0;
        callQualityTitleLabel.Text = "Call Quality Guard";
        callQualityGuardCheckBox.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        callQualityGuardCheckBox.AutoSize = true;
        callQualityGuardCheckBox.Checked = true;
        callQualityGuardCheckBox.CheckState = CheckState.Checked;
        callQualityGuardCheckBox.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
        callQualityGuardCheckBox.Location = new Point(340, 10);
        callQualityGuardCheckBox.Name = "callQualityGuardCheckBox";
        callQualityGuardCheckBox.Size = new Size(68, 19);
        callQualityGuardCheckBox.TabIndex = 1;
        callQualityGuardCheckBox.Text = "Enabled";
        callQualityGuardCheckBox.UseVisualStyleBackColor = false;
        callQualityGuardCheckBox.CheckedChanged += callQualityGuardCheckBox_CheckedChanged;
        callQualityStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        callQualityStatusLabel.AutoEllipsis = true;
        callQualityStatusLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        callQualityStatusLabel.ForeColor = Color.FromArgb(36, 120, 90);
        callQualityStatusLabel.Location = new Point(12, 34);
        callQualityStatusLabel.Name = "callQualityStatusLabel";
        callQualityStatusLabel.Size = new Size(396, 22);
        callQualityStatusLabel.TabIndex = 2;
        callQualityStatusLabel.Text = "Checking audio route...";
        callQualityDetailLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        callQualityDetailLabel.AutoEllipsis = true;
        callQualityDetailLabel.ForeColor = Color.FromArgb(80, 88, 98);
        callQualityDetailLabel.Location = new Point(12, 58);
        callQualityDetailLabel.Name = "callQualityDetailLabel";
        callQualityDetailLabel.Size = new Size(396, 34);
        callQualityDetailLabel.TabIndex = 3;
        callQualityDetailLabel.Text = "Detecting AirPods Hands-Free profile.";
        callQualityFixButton.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        callQualityFixButton.BackColor = Color.FromArgb(10, 92, 190);
        callQualityFixButton.FlatAppearance.BorderSize = 0;
        callQualityFixButton.FlatStyle = FlatStyle.Flat;
        callQualityFixButton.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
        callQualityFixButton.ForeColor = Color.White;
        callQualityFixButton.Location = new Point(12, 96);
        callQualityFixButton.Name = "callQualityFixButton";
        callQualityFixButton.Size = new Size(196, 26);
        callQualityFixButton.TabIndex = 4;
        callQualityFixButton.Text = "Fix route";
        callQualityFixButton.UseVisualStyleBackColor = false;
        callQualityFixButton.Click += callQualityFixButton_Click;
        callQualitySettingsButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        callQualitySettingsButton.BackColor = Color.White;
        callQualitySettingsButton.FlatAppearance.BorderColor = Color.FromArgb(205, 213, 224);
        callQualitySettingsButton.FlatStyle = FlatStyle.Flat;
        callQualitySettingsButton.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
        callQualitySettingsButton.ForeColor = Color.FromArgb(28, 34, 42);
        callQualitySettingsButton.Location = new Point(216, 96);
        callQualitySettingsButton.Name = "callQualitySettingsButton";
        callQualitySettingsButton.Size = new Size(192, 26);
        callQualitySettingsButton.TabIndex = 5;
        callQualitySettingsButton.Text = "Sound settings";
        callQualitySettingsButton.UseVisualStyleBackColor = false;
        callQualitySettingsButton.Click += callQualitySettingsButton_Click;
        metaGrid.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        metaGrid.ColumnCount = 2;
        metaGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 78F));
        metaGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        metaGrid.Controls.Add(statusLabel, 0, 0);
        metaGrid.Controls.Add(statusValueLabel, 1, 0);
        metaGrid.Controls.Add(connectedLabel, 0, 1);
        metaGrid.Controls.Add(connectedValueLabel, 1, 1);
        metaGrid.Controls.Add(signalLabel, 0, 2);
        metaGrid.Controls.Add(signalValueLabel, 1, 2);
        metaGrid.Controls.Add(addressLabel, 0, 3);
        metaGrid.Controls.Add(addressValueLabel, 1, 3);
        metaGrid.Location = new Point(20, 500);
        metaGrid.Name = "metaGrid";
        metaGrid.RowCount = 4;
        metaGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        metaGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        metaGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        metaGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        metaGrid.Size = new Size(424, 120);
        metaGrid.TabIndex = 7;
        foreach (var label in new[] { statusLabel, connectedLabel, signalLabel, addressLabel })
        {
            label.Dock = DockStyle.Fill;
            label.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            label.ForeColor = Color.FromArgb(80, 88, 98);
            label.TextAlign = ContentAlignment.MiddleLeft;
        }
        statusLabel.Text = "Status";
        connectedLabel.Text = "Windows";
        signalLabel.Text = "Signal";
        addressLabel.Text = "Address";
        foreach (var label in new[] { statusValueLabel, connectedValueLabel, signalValueLabel, addressValueLabel })
        {
            label.AutoEllipsis = true;
            label.Dock = DockStyle.Fill;
            label.TextAlign = ContentAlignment.MiddleLeft;
        }
        rawValueBox.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        rawValueBox.BackColor = Color.FromArgb(250, 251, 252);
        rawValueBox.BorderStyle = BorderStyle.FixedSingle;
        connectedValueLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        connectedValueLabel.ForeColor = Color.FromArgb(10, 92, 190);
        rawValueBox.Location = new Point(20, 636);
        rawValueBox.Multiline = true;
        rawValueBox.Name = "rawValueBox";
        rawValueBox.ReadOnly = true;
        rawValueBox.ScrollBars = ScrollBars.Both;
        rawValueBox.Size = new Size(424, 104);
        rawValueBox.TabIndex = 8;
        rawValueBox.WordWrap = false;
        trayMenu.Items.AddRange(new ToolStripItem[] { openMenuItem, refreshMenuItem, trayListeningModeMenuItem, trayCallQualitySeparator, trayCallQualityGuardMenuItem, exitMenuItem });
        openMenuItem.Text = "Open";
        openMenuItem.Click += openMenuItem_Click;
        refreshMenuItem.Text = "Stop scan";
        refreshMenuItem.Click += refreshMenuItem_Click;
        trayListeningModeMenuItem.DropDownItems.AddRange(new ToolStripItem[] { trayTransparencyMenuItem, trayAdaptiveMenuItem, trayNoiseCancelMenuItem });
        trayListeningModeMenuItem.Text = "Listening mode";
        trayTransparencyMenuItem.Text = "Transparency";
        trayTransparencyMenuItem.Click += trayTransparencyMenuItem_Click;
        trayAdaptiveMenuItem.Text = "Adaptive";
        trayAdaptiveMenuItem.Click += trayAdaptiveMenuItem_Click;
        trayNoiseCancelMenuItem.Text = "Noise Cancel";
        trayNoiseCancelMenuItem.Click += trayNoiseCancelMenuItem_Click;
        trayCallQualityGuardMenuItem.DropDownItems.AddRange(new ToolStripItem[] { trayCallQualityEnabledMenuItem, trayApplyCallQualityFixMenuItem, trayOpenSoundSettingsMenuItem });
        trayCallQualityGuardMenuItem.Text = "Call Quality Guard";
        trayCallQualityEnabledMenuItem.Checked = true;
        trayCallQualityEnabledMenuItem.CheckOnClick = true;
        trayCallQualityEnabledMenuItem.CheckState = CheckState.Checked;
        trayCallQualityEnabledMenuItem.Text = "Enabled";
        trayCallQualityEnabledMenuItem.Click += trayCallQualityEnabledMenuItem_Click;
        trayApplyCallQualityFixMenuItem.Text = "Fix audio route";
        trayApplyCallQualityFixMenuItem.Click += trayApplyCallQualityFixMenuItem_Click;
        trayOpenSoundSettingsMenuItem.Text = "Open Sound settings";
        trayOpenSoundSettingsMenuItem.Click += trayOpenSoundSettingsMenuItem_Click;
        exitMenuItem.Text = "Exit";
        exitMenuItem.Click += exitMenuItem_Click;
        notifyIcon.ContextMenuStrip = trayMenu;
        notifyIcon.Text = "WinPods";
        notifyIcon.Visible = true;
        notifyIcon.DoubleClick += notifyIcon_DoubleClick;
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.White;
        ClientSize = new Size(1100, 562);
        Controls.Add(rootLayout);
        Font = new Font("Segoe UI", 9F);
        MinimumSize = new Size(980, 540);
        Name = "Form1";
        Padding = new Padding(18);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "WinPods";
        rootLayout.ResumeLayout(false);
        headerPanel.ResumeLayout(false);
        headerPanel.PerformLayout();
        mainSplit.Panel1.ResumeLayout(false);
        mainSplit.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)mainSplit).EndInit();
        mainSplit.ResumeLayout(false);
        devicesPanel.ResumeLayout(false);
        devicesPanel.PerformLayout();
        sortMenu.ResumeLayout(false);
        detailPanel.ResumeLayout(false);
        detailPanel.PerformLayout();
        batteryGrid.ResumeLayout(false);
        leftBatteryPanel.ResumeLayout(false);
        leftBatteryPanel.PerformLayout();
        rightBatteryPanel.ResumeLayout(false);
        rightBatteryPanel.PerformLayout();
        caseBatteryPanel.ResumeLayout(false);
        caseBatteryPanel.PerformLayout();
        listeningModePanel.ResumeLayout(false);
        callQualityPanel.ResumeLayout(false);
        callQualityPanel.PerformLayout();
        metaGrid.ResumeLayout(false);
        trayMenu.ResumeLayout(false);
        ResumeLayout(false);
    }
}
